### PR TITLE
create content with metadata

### PR DESCRIPTION
**Pull request by ThePlenkov**
Implements #54

### CODE REVIEW

**Comment by MrRefactoring** [comment]
You touching Cloud Api code, for server we have separate code base here: https://github.com/MrRefactoring/confluence.js/tree/master/src/server

**Comment by ThePlenkov** [comment]
Yes, I was trying actually to understand that. Meanwhile I see that at least createContent model type is shared one:

https://github.com/MrRefactoring/confluence.js/blob/6ca7678910da7b48f3b973bcc281f7b17db1fbcc/src/server/parameters/createContent.ts#LL1C1-L1C1

**Comment by ThePlenkov** [comment]
meanwhile.. I've tried to create a new page with metadata - but actual properties stay empty. I was only able to create custom properties by a separate createContentProperty call. Not sure - may be is related to our server version. It could be nice to check if we can define additional properties along with page creation with a single call

**Comment by ThePlenkov** [comment]
i decided to close since this change doesn't bring the impact

**Pull request closed without merging**
